name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Ajuste para o branch que você utiliza

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t gusttarizerio/vertex:imagem-java-vertex .

      # Push da imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push gusttarizerio/vertex:imagem-java-vertex
